server:
  port: 8081
  servlet:
    context-path: /student-provider
  tomcat:
    use-relative-redirects: false

spring:
  application:
    name: student-provider
  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
    zookeeper:
      connect-string: localhost:2181  # ZooKeeper 地址
      enabled: true
      discovery:
        prefer-ip-address: true
        enabled: true
        root: /services  # 可选：自定义根路径（默认是 /services）
        instance-id: ${spring.application.name}:${server.port} # 唯一实例ID
  ai:
    dashscope:
      api-key: sk-f637a6d845ba45c9ae49fb6de12f80c6  # ← 替换成你自己的

management:
  endpoints:
    web:
      exposure:
        include: "*"

